---
title: "Academic and Professional Experience"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: darkly
---

# Education
**Columbia University** – Mailman School of Public Health (MSPH), New York, NY                                                    
Master of Public Health in _Epidemiology_

Certificate in _Applied Biostatistics_

Expected: May 2020

 $~$
 
**Ithaca College**, Ithaca, NY			           	

Bachelor of Arts in **Mathematics** with Honors	Minors in _Economics_, _Finance_, and _Honors Program_

May 2018

$~$

# Scholarly Presentations
•	_Predicting U.S. Childhood Obesity through Mathematical Modeling_                        

Presented 5 times including: National Conferences on Undergraduate Research (NCUR), National Conference for Undergraduate Women in Mathematics, Mathematical Association of America National MathFest     

May 2017 - Apr. 2018

 $~$
 
•	_Research Experience through Summer Scholars Program_, Ithaca College, Ithaca, NY

Presented at H&S Summer Research Exhibition and Humanities & Sciences Department      

Nov. & Oct. 2017

 $~$
 
•	_Expressing Egyptian Fractions with Hexagonal and Triangular Numbers_
Ithaca College’s Academic Symposium (May 2015)  &  Mathematical Association of America Section Conference                   

Apr. 2015

 $~$
 
# Professional Experience

•	**Data Analyst Intern**, Antidote Inc., NYC, NY 								         
Feb. 2019-Current

Maintaining/interpreting large dataset using SAS to identify research questions and conducting relevant analyses for a series of white papers based on recent survey on engaging patients in clinical trials as stakeholders rather than subjects

 $~$
 
•	**Mathematics in Honors Research**, Ithaca College, Ithaca, NY			                                                           		               Aug. 2017-May 2018 

Investigated existing SIR epidemic models to create a model representing childhood obesity in the U.S. 

Applied statistical analysis in numerically forming the parameters based on social and biological                  determinants of health for the model of children in the U.S. 

 $~$
 
•	**Mathematics Capstone**, Ithaca College, Ithaca, NY		                         	                                                                Aug. 2017-May 2018 

Explored epidemiological mathematics of infectious diseases by predicting interactions of people                                and diseases through varying epidemic, endemic, and herd immunity models 

Connected newly learned research to mathematics learned in previous coursework

 $~$
 
•	**Humanities and Sciences Summer Scholars Research Program**, Ithaca College, Ithaca, NY                                       		     

May 2017-Aug. 2017

Accepted into prestigious, 20-person, paid, 8-week, independent research program

Developed major ideas and fundamentals for the continued research of mathematical modeling in                                 U.S. childhood obesity as part of Mathematics in Honors Research

 $~$
 
•	**Grader for the Mathematics Department**, Ithaca College, Ithaca, NY                	                                    		               
Aug. 2016-May 2018

 $~$
 
•	**Research in Number Theory**, Ithaca College, Ithaca, NY			        

Oct. 2014-May 2015 

 $~$
 
•	**Pool Manager**, Holland Municipal, Milford, NJ

Summers 2013-2016, 2018

$~$

# Leadership Experience
•	**Vice President of Operations**, _Healthcare Data Analytics_, Columbia University, MSPH, New York, NY	                                

Dec. 2018-Current

Collaborating with other organizations to host a first-ever Healthcare Hackathon at CUMC based on a local problem

$~$

•	**Treasurer**, _Pi Mu Epsilon_, Ithaca College, Ithaca, NY	  

Mar. 2017-May 2018

$~$

•	**Director of Finance**, _Junior Class Community Council_, Ithaca College, Ithaca, NY                  
Oct. 2016-May 2017

$~$

•	**Vice President**, _National Residence Hall Honorary_, Ithaca College, Ithaca, NY                                           
Jan. 2016-May 2017

$~$

# Additional Experience
•	_Senior Class Cabinet_, Ithaca College, Ithaca, NY				    
Aug. 2017-May 2018

$~$

•	_Pitch Please a cappella group_, Ithaca College, Ithaca, NY	       	                                

Aug. 2014-May 2018

$~$

•	_Students Today, Alumni Tomorrow_, Ithaca College, Ithaca, NY		                             

Sep. 2014-May 2018

$~$

# Skills
•	E-Views, Statistical Program 

• LaTeX – Proficient

• Microsoft Office (Including Access)

•	R

•	SAS

• STATA 

• SQL

$~$ 

# Certificates
•	Citi Program – certified                         • HIPPA – certified


