---
title: "dashboard"
output:
  html_document:
    toc: true
    toc_float: true
    theme: darkly
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
data("instacart")
```

```{r}
set.seed(1)

instacart = instacart %>%
  sample_n(4000)

# Scatterplot
instacart%>%
  mutate(text_label = str_c("Order Hour of the Day: ", order_hour_of_day)) %>%
  plot_ly(
    x = ~product_name, y = ~order_dow, type = "scatter", mode = "markers", color = ~order_hour_of_day, text = ~text_label, alpha = 0.5
  )
```
```{r}
#Barplot
instacart%>%
  mutate(text_label = str_c("Order Hour of the Day: ", order_hour_of_day)) %>%
  plot_ly(
    x = ~product_name, y = ~order_dow, type = "bar", mode = "markers", color = ~order_hour_of_day, text = ~text_label, alpha = 0.5
  )
```


```{r}
#Barplot w/ order
instacart%>%
  count(aisle) %>%
  mutate(aisle = fct_reorder(aisle, n)) %>%
  plot_ly(
    x = ~aisle, y = ~n, type = "bar", color = ~aisle
  )
```
#Barplot w/ order
```{r}
instacart%>%
  count(department) %>%
  mutate(department = fct_reorder(department, n)) %>%
  plot_ly(
    x = ~department, y = ~n, type = "bar", color = ~department
  )



instacart%>%
  count(department) %>%
  mutate(department = fct_reorder(department, n)) %>%
  plot_ly(
    x = ~department, y = ~n, type = "box", color = ~department
  )
```

# Top 15 Aisle Ordered from and Their Corresponding Day of the Week
```{r}
instacart_new = 
  instacart%>%
  count(aisle, sort = TRUE) %>%
  top_n(15) %>%
  select(aisle)

inner_join(instacart, instacart_new, by = "aisle") %>%
  mutate(aisle = fct_reorder(aisle, order_dow)) %>%
  plot_ly(y = ~order_dow, color = ~aisle, type = "box"
  ) %>%
  layout(
    title = "Top 15 Aisle Ordered from and \nTheir Corresponding Day of the Week",
    xaxis = list(title = "Aisle Name"),
      yaxis = list(title = "Day of Week")
    )

```

